// El banco y las respuestas se usan exclusivamente en la función del servidor.
export const QUESTIONS = [
  { id:'mapa', text:'Según el curso, ¿qué describen principalmente los CGPE?', options:['Los supuestos económicos y la orientación de política pública.','El impuesto definitivo de cada empresa.','Las facturas que debe emitir cada contribuyente.','Las sanciones individuales impuestas por el SAT.'], correct:0 },
  { id:'vigencia', text:'Antes de aplicar una propuesta fiscal a una empresa, ¿qué debe verificarse?', options:['Que se haya comentado en un evento empresarial.','El texto aplicable, su publicación, vigencia y requisitos.','Que aparezca en una proyección económica.','Que otra empresa ya la esté utilizando.'], correct:1 },
  { id:'base', text:'Si la tasa de ISR permanece igual, ¿qué puede modificar el impuesto del ejercicio?', options:['Únicamente el nombre comercial de la empresa.','Únicamente el banco donde se recibe el pago.','Los cambios en deducciones, pérdidas y base gravable.','El formato visual del presupuesto empresarial.'], correct:2 },
  { id:'perdidas', text:'En el caso hipotético: utilidad de $1,000,000, pérdidas utilizables de $1,000,000, tope de pérdidas del 50% de la utilidad y tasa del 30%. Sin otros ajustes, ¿cuál es el ISR con ese tope?', options:['$0.','$150,000.','$300,000.','$500,000.'], correct:1 },
  { id:'plazo', text:'En el curso, ¿por qué un plazo mayor para utilizar pérdidas no implica necesariamente pagar menos hoy?', options:['Porque elimina toda obligación de llevar contabilidad.','Porque convierte las pérdidas en un reembolso inmediato.','Porque garantiza que todos los saldos anteriores sigan vigentes.','Porque puede coexistir con un límite anual para disminuirlas.'], correct:3 },
  { id:'resico', text:'¿Qué conviene revisar al comparar una opción de RESICO para una empresa?', options:['Solo que los ingresos estén por debajo de un umbral.','Solo el porcentaje que aparezca en un titular.','La elegibilidad, los requisitos y el efecto con datos reales.','La preferencia del proveedor por un tipo de factura.'], correct:2 },
  { id:'iva-a', text:'Caso hipotético A: ventas gravadas cobradas sin IVA de $100,000 e IVA acreditable de $4,000. Compara 16% menos acreditable contra una opción supuesta de 7% sin acreditar. Sin otros ajustes, ¿qué ocurre con la opción?', options:['El pago aumenta $5,000.','El pago disminuye $5,000.','Ambos pagos son de $7,000.','La opción genera un saldo a favor de $4,000.'], correct:1 },
  { id:'iva-b', text:'Caso hipotético B: ventas gravadas cobradas sin IVA de $100,000 e IVA acreditable de $12,000. Compara 16% menos acreditable contra una opción supuesta de 7% sin acreditar. Sin otros ajustes, ¿qué ocurre con la opción?', options:['El pago aumenta $3,000.','El pago disminuye $3,000.','Ambos pagos son de $4,000.','La opción elimina el pago mensual.'], correct:0 },
  { id:'soporte', text:'¿Qué conjunto de información ayuda a documentar una operación, según el curso?', options:['Solo una captura del saldo bancario.','Solo el presupuesto del siguiente ejercicio.','Solo una explicación verbal del proveedor.','Contrato, CFDI, pago y evidencia de la entrega o servicio.'], correct:3 },
  { id:'plan', text:'¿Cuál es el primer paso del plan de treinta días propuesto en el curso?', options:['Ejecutar todas las propuestas antes de su publicación.','Ordenar la información e identificar el tema prioritario.','Cambiar de régimen sin comparar escenarios.','Posponer la revisión hasta recibir un requerimiento.'], correct:1 }
];
